version: "3.8"

services:
  spanner:
    image: gcr.io/cloud-spanner-emulator/emulator
    ports:
      - "9020:9020"
      - "9010:9010"
  spanner-init:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    links:
      - spanner
    command: >
      bash -c 'gcloud config configurations create emulator &&
              gcloud config set auth/disable_credentials true &&
              gcloud config set project local-project &&
              gcloud config set api_endpoint_overrides/spanner http://spanner:9020/ &&
              gcloud config set auth/disable_credentials true &&
              gcloud spanner instances create test-instance --config=emulator-config --description=Emulator --nodes=1'
  redis-shard-1:
    image: redis:5-alpine
    ports:
      - "6379:6379"
  redis-shard-2:
    image: redis:5-alpine
    ports:
      - "6380:6379"
  postgres-shard-1:
    image: postgres:12.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: password
  postgres-shard-2:
    image: postgres:12.3
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: password


