name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  transactor-test:
    name: test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: checkout
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
      - name: checkout
        if: github.event_name == 'push'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: setup
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.34.1
          args: --timeout=5m0s
      - name: install deps
        run: go mod download
      - name: test
        run: go test -v .